# Generated by Django 4.2.3 on 2023-08-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Namanblogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popularblogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_name', models.CharField(max_length=25)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('blog_title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Regularblogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_name', models.CharField(max_length=25)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('blog_title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
